image: rust:buster


before_script:
  - apt-get update
  - apt-get install -y libsdl2-dev libsdl2-ttf-dev libsdl2-gfx-1.0.0 libsdl2-gfx-dev

compile:
  stage: build
  script:
    - cargo build --verbose --features gfx --features ttf

